# Generated by Django 6.1.1 on 2026-09-22 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('numero_documento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(blank=True, max_length=100)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(blank=True, max_length=100)),
                ('tipo_documento', models.CharField(max_length=30)),
                ('telefono_1', models.CharField(max_length=30)),
                ('telefono_2', models.CharField(blank=True, max_length=30)),
                ('telefono_3', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'acudiente',
                'ordering': ['apellido_1', 'nombre_1'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('dia_semana', models.CharField(max_length=20)),
                ('tipo_jornada', models.CharField(choices=[('Desarrollo Cognitivo', 'Desarrollo Cognitivo'), ('Musical', 'Musical')], max_length=30)),
            ],
            options={
                'db_table': 'jornada',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('ti', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(blank=True, max_length=100)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(blank=True, max_length=100)),
                ('identificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('acudiente', models.ForeignKey(db_column='numero_documento_acudiente', on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='core.acudiente')),
            ],
            options={
                'db_table': 'alumno',
                'ordering': ['apellido_1', 'nombre_1'],
            },
        ),
        migrations.CreateModel(
            name='ClaseProgramada',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='core.jornada')),
            ],
            options={
                'db_table': 'clase_programada',
                'ordering': ['-fecha', 'id_clase'],
            },
        ),
        migrations.CreateModel(
            name='AlumnoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(db_column='ti', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.alumno')),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.claseprogramada')),
            ],
            options={
                'db_table': 'alumno_clase',
                'constraints': [models.UniqueConstraint(fields=('alumno', 'clase'), name='uq_alumno_clase_alumno_clase')],
            },
        ),
    ]
