# Generated by Django 6.1.1 on 2026-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
