# Generated by Django 6.1.1 on 2026-09-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acudiente_correo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "alumno_clase" DROP COLUMN IF EXISTS "id";',
                    reverse_sql=(
                        'ALTER TABLE "alumno_clase" '
                        'ADD COLUMN "id" bigint GENERATED BY DEFAULT AS IDENTITY;'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='alumnoclase',
                    name='id',
                ),
            ],
        ),
        migrations.AddField(
            model_name='alumnoclase',
            name='pk',
            field=models.CompositePrimaryKey('alumno', 'clase', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
