# Generated by Django 6.1.1 on 2026-09-28 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alumno_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('clases_pagadas', models.PositiveIntegerField()),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alumno', models.ForeignKey(db_column='ti_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.alumno')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha_pago', '-id_pago'],
            },
        ),
    ]
