# Generated by Django 6.1.1 on 2026-09-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='programada', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.claseprogramada')),
            ],
            options={
                'db_table': 'asistencia',
                'ordering': ['-clase__fecha', '-id_asistencia'],
                'constraints': [models.UniqueConstraint(fields=('alumno', 'clase'), name='uq_asistencia_alumno_clase')],
            },
        ),
    ]
