# Generated by Django 6.1.1 on 2026-09-28 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('acudiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversacion', to='core.acudiente')),
            ],
            options={
                'db_table': 'conversacion',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajeria/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('leido_por_acudiente', models.BooleanField(default=False)),
                ('leido_por_personal', models.BooleanField(default=False)),
                ('automatico', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacion')),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensaje',
                'ordering': ['creado_en', 'id'],
            },
        ),
    ]
