# Generated by Django 6.1.1 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_automatizacion_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(
                choices=[
                    ('programada', 'Programada'),
                    ('presente', 'Presente'),
                    ('ausente', 'Ausente'),
                    ('pospuesta', 'Pospuesta'),
                ],
                default='programada',
                max_length=20,
            ),
        ),
    ]