# Generated by Django 6.1.1 on 2026-10-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_asistencia_pospuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaClase',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_recurrente', models.BooleanField(default=True)),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal')], default='semanal', max_length=20)),
                ('jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.PROTECT, related_name='plantillas', to='core.jornada')),
            ],
            options={
                'db_table': 'plantilla_clase',
                'ordering': ['fecha_inicio', 'id_plantilla'],
            },
        ),
        migrations.AddField(
            model_name='claseprogramada',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_generadas', to='core.plantillaclase'),
        ),
        migrations.CreateModel(
            name='ExcepcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('accion', models.CharField(choices=[('agregar', 'Agregar estudiante'), ('quitar', 'Quitar estudiante')], default='agregar', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_clase', to='core.alumno')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='core.plantillaclase')),
            ],
            options={
                'db_table': 'excepcion_clase',
                'constraints': [models.UniqueConstraint(fields=('plantilla', 'fecha', 'alumno'), name='uq_excepcion_plantilla_fecha_alumno')],
            },
        ),
        migrations.CreateModel(
            name='PlantillaClaseAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_clase', to='core.alumno')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='core.plantillaclase')),
            ],
            options={
                'db_table': 'plantilla_clase_alumno',
                'constraints': [models.UniqueConstraint(fields=('plantilla', 'alumno'), name='uq_plantilla_alumno_alumno')],
            },
        ),
    ]
