# Generated by Django 6.0.8 on 2026-10-10 14:56

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_legacy_auth_and_push(apps, schema_editor):
    apps.get_model('core', 'PushSubscription').objects.all().delete()
    apps.get_model('authtoken', 'Token').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pushsubscription'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.CharField(max_length=64)),
                ('key', models.CharField(default=core.models.generate_session_key, editable=False, max_length=64, unique=True)),
                ('nombre_dispositivo', models.CharField(max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_dispositivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesion_dispositivo',
                'ordering': ['-ultimo_uso'],
            },
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core.sesiondispositivo'),
        ),
        migrations.CreateModel(
            name='TicketWebSocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=core.models.generate_websocket_ticket, editable=False, max_length=64, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_websocket', to='core.sesiondispositivo')),
            ],
            options={
                'db_table': 'ticket_websocket',
            },
        ),
        migrations.RunPython(clear_legacy_auth_and_push, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pushsubscription',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core.sesiondispositivo'),
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='usuario',
        ),
        migrations.AddConstraint(
            model_name='sesiondispositivo',
            constraint=models.UniqueConstraint(fields=('usuario', 'dispositivo_id'), name='uq_sesion_usuario_dispositivo'),
        ),
    ]
